#!/bin/csh
#This is an example C shell script used to run the Nano-Pore-Analyzer code
# This C shell script is placed in a directory where
# several subdirectories include VASP output files to be used.
#The script copies the EIGENVAL, OSZICAR, and CONTCAR VASP files along with NAME.txt from
#the directories, and then runs the code using "./hello"
#The data is written out to "DATA.csv" and the cluster files in POSCAR format are moved back to the
#crystal's directory

set j = $PWD
set k = ~/work/group/codes/Nano-Pore-Analyzer
set i = 1

cd ./Crystal/
echo "crystal" > IS_CRYSTAL.txt
cp IS_CRYSTAL.txt ./..
cp EIGENVAL ./..
cp OSZICAR ./..
cp CONTCAR ./..
echo "$PWD" > NAME.txt
cp NAME.txt ./..
cd ./..
./hello
rm IS_CRYSTAL.txt

#while($i < 13)
#cd ./$i
#echo "$PWD" > NAME.txt
#cp NAME.txt $k/.
#cp EIGENVAL $k/.
#cp OSZICAR $k/.
#cp CONTCAR $k/.
#cd $k
#./hello
#mv CARBONS.vasp ./../../results/CC_models/72Mixed_surf_CC/$i
#mv SILICON.vasp ./../../results/CC_models/72Mixed_surf_CC/$i
#@ i++
#end
#mv DATA.csv $j/.

