#!/bin/csh
#This is an example C shell script used to run the Nano-Pore-Analyzer 
#For example, this C shell script is placed outside of the directory "Combined_Code" where
#all of the source files, along with "DATA.csv", are placed.
#The script copies the EIGENVAL, OSZICAR, and CONTCAR VASP files from
#the directories of certain crystal models, and then runs the code using "./hello"
#The data is written out to "DATA.csv" and the appropriate files are moved back to the
#crystal's directory


set S = "S"
set C = "C"
set i = 1
while($i < 13)
cd ./../results/CC_models/72Mixed_surf_CC/$i
cp EIGENVAL ./../../../../codes/Combined_Code/
cp OSZICAR ./../../../../codes/Combined_Code
cp CONTCAR ./../../../../codes/Combined_Code
cd ./../../../../codes/Combined_Code
./hello
mv CARBONS.vasp ./../../results/CC_models/72Mixed_surf_CC/$i
mv SILICON.vasp ./../../results/CC_models/72Mixed_surf_CC/$i
cd ..
@ i++
end
